version: '3'

services:
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        restart: unless-stopped
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - sandbox

    postgres:
        container_name: pdb
        image: postgres:latest
        ports:
            - '5432:5432'
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        volumes:
            - ./packages/api-postgres/data/postgres:/var/lib/postgresql/data
        networks:
            - sandbox

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - ./packages/api-postgres/data/pgadmin:/var/lib/pgadmin
        networks:
            - sandbox

networks:
    sandbox:
        driver: bridge
