version: '3'

services:
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        restart: unless-stopped
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - sandbox

    postgres:
        image: postgres:11.5
        container_name: pdb
        ports:
            - '5432:5432'
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
        networks:
            - sandbox
        volumes:
            - ./packages/api-postgres/data/postgres:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - ./packages/api-postgres/data/pgadmin:/root/.pgadmin
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        networks:
            - sandbox
        restart: unless-stopped

networks:
    sandbox:
        driver: bridge
