import { gql } from 'apollo-server-express';

export default gql`
    "A simple User type"
    type User {
        "The unique id for this user generated by MongoDB"
        _id: ID!

        "User's first and last names"
        name: Name

        "User's email address"
        email: String

        "User's password; this will be hashed very soon :-)"
        password: String

        isEmailVerified: Boolean
        emailVerificationToken: String

        createdAt: String
        updatedAt: String
    }

    type Name {
        first: String
        last: String
    }

    input NameInput {
        first: String!
        last: String!
    }

    input UserInput {
        "User's first and last names"
        name: NameInput!

        "User's email address"
        email: String!
    }

    type LoginResponse {
        authUser: User
        token: String
    }
`;
