name: API Postgres test
on: [push]
jobs:
    build:
        name: API test
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready --health-interval 10s --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up test database
              run: |
# docker exec -i postgres bash < ./db-setup.sh
                  docker container ls -a
                  docker container ls -aq
