name: API Postgres test

on: [push, pull_request]

jobs:
    runner-job:
        name: API test
        runs-on: ubuntu-latest
        env:
            ACCESS_TOKEN_SECRET: AccesstokenSECRETforTESTING
            REFRESH_TOKEN_SECRET: RefreshtokenSECRETforTESTING

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready --health-interval 10s --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - name: Check PWD
              run: pwd
              
            - name: Set up test database
              run: |
                  docker exec -i $(docker container ls -aq) bash < ./packages/api-postgres/scripts/db-setup.sh

            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm install

            - name: Run API tests
              run: npm run test:api-p
